language: java

jdk:
  - oraclejdk8
  - openjdk10
  - openjdk11
  
cache:
  directories:
    - $HOME/.m2
    - .cache

script:
  - mvn -D environment=test verify
  # make sure javadocs are ok too
  - mvn -P release javadoc:javadoc
