language: java

jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - .cache

# override default command since it doesn't skip checkstyle
install:
  - tools/install-repackaged

script:
  - mvn -D environment=test verify
